In [3]:
#n the script belo we first imported the numpy library as np
import numpy as np
print (np. version)


<module 'numpy.version' from 'C:\\Users\\lsh1900356\\anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [5]:
# the array method
#list of numbers
x=[2,3,4,5,6] #list
num=np.array(x)
num
#creating numy array using np.array
#nums=np.array(x)
#display
#the above code creates a 1-D array


array([2, 3, 4, 5, 6])

In [6]:
# get dimension (1-D array)
#nums.ndim
num.ndim

1

In [7]:
#returns a tuple with each index hving the number of corresponding elements 
#0,1,2,3...n
#nums.shape
#represents the elements (not the index)
num.shape 
# the commer in the result is due to the fact that we have a vector (1-dimension)

(5,)

In [8]:
#Get type
#nums.dtype
num.dtype


dtype('int32')

In [9]:
#length of one array element in bytes (if worried about your memory)
#nums.itemsize
num.itemsize

4

In [11]:
#get total size total bytes consumed by the elements of the array
num.nbytes

20

In [12]:
#get number of elements 
num.size

5

In [13]:
##Scalar 
#0-D arrays, or scalars
#arr=np.array(42)
#display
arr=np.array(100)
print(arr)
arr.size

100


1

In [14]:
##vector
#1-D Arrays. Array tha has 0-D arrays as its elements is called uni-dimensional or 
y= [1,2,3,4,5]
arr=np.array(y)
arr.size
#display

#annual_income=[]

5

In [18]:
##Matrix 
#An array that has 1-D arrays as it elements is called a 2-D array.These are alsways used to 
#create two lists

#arr = np.array([[1,2,3], [4,5,6]])
matrix = np.array([[3, 6], [7, 88]])
matrix
#print(arr)

array([[ 3,  6],
       [ 7, 88]])

In [20]:
#alternatively 
x=[3.5, 6.6]
y=[7.0, 8.0]
matrix = np.array([x,y])
matrix

array([[3.5, 6.6],
       [7. , 8. ]])

In [21]:
##Tensor
#3-D arrays. #3 lists
#an array hat has 2-d arrays (matrices) as its elements is called 3-D array
#these are often used to represent a 3rd order tensor.
arr=np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [22]:
##Arrange method 
#start, end index
twodim = np.arange(2,8)
twodim
#display

array([2, 3, 4, 5, 6, 7])

In [24]:
#Now let's add a step size of 2 to our array and see what happens:
nums = np.arange (50,100,20)
nums

array([50, 70, 90])

In [28]:
nums = np.arange (50,101,3)
nums

array([50, 53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])